language: node_js
node_js:
  - 8
  
cache:
  yarn: true
  directories:
    - node_modules

before_install:
  - echo I am before installed
  - echo $TRAVIS_TAG

install:
  - echo I am install
  - yarn install

before_script:
  - echo I am before_script

after_success:
  - echo I am after_success

after_failure:
  - echo I am after_failure

before_deploy:
  - echo I am before_deploy

after_script:
  - echo I am after_script

script:
  - echo I am script
  - yarn build
  - yarn test

stages:
  - name: deploy

jobs:
  include:
    - stage: build
      name: ECS Build
      env:
        - ENV=dev ENV2=QA
        - ENV3=sc ENV4=prod
      script: yarn test
      script: echo Another parallel job
    - stage: deploy
      name: ECS Deploy
      env:
        - ENV=dev ENV2=QA
        - ENV3=sc ENV4=prod
      script: echo Deploying Job
