language: node_js
node_js:
  - 8
  
cache:
  yarn: true
  directories:
    - node_modules

before_install:
  - echo I am before installed

install:
  - echo I am install
  - yarn

before_script:
  - echo I am before_script

after_success:
  - echo I am after_success

after_failure:
  - echo I am after_failure

before_deploy:
  - echo I am before_deploy

after_script:
  - echo I am after_script

script:
  - echo I am script
  - yarn build
  - yarn test

env:
  - ENV=dev
  - ENV=qa

stages:
  - name: deploy
    if: branch = master and type = pull_request
  - name: build
    if: branch = branch1 and type = pull_request

jobs:
  include:
    - stage: deploy
      name: ECS deployment
      script:
        - echo "Deploying to ECS"
    - stage: build
      name: NPM Build
      script:
        - echo "Building YARN"
