language: node_js
node_js:
  - 8
  
cache:
  yarn: true
  directories:
    - node_modules

before_install:
  - echo I am before installed
  - echo $TRAVIS_TAG

install:
  - echo I am install
  - yarn install

before_script:
  - echo I am before_script

after_success:
  - echo I am after_success

after_failure:
  - echo I am after_failure

before_deploy:
  - echo I am before_deploy

after_script:
  - echo I am after_script

jobs:
  include:
    - stage: build
      script: ./tester 1
      script: ./tester 2
    - stage: deploy
      script: ./deploy
