language: node_js
node_js:
  - 8

cache:
  yarn: true
  directories:
    - node_modules

before_install:
  - echo I am before installed
  - echo $TRAVIS_TAG

install:
  - echo I am install
  - yarn install

before_script:
  - echo I am before_script

after_success:
  - echo I am after_success

after_failure:
  - echo I am after_failure

stages:
  - name: test
  - name: build

jobs:
  include:
    - stage: test
      name: ECS deployment
      env:
        - ENV=dev ENV2=QA
        - ENV3=sc ENV4=prod
      script:
        - echo "unit test"
        - echo 'SOmethinbg'
    - script: echo 'integration test'
    - stage: build
      name: NPM Build
      env:
        - ENV=dev ENV2=QA
        - ENV3=sc ENV4=prod
      script:
        - echo "Building YARN"
        - echo $ENV
        - echo $ENV2
        - echo $ENV3
        - echo $ENV4
